{% set name = "gnuradio-sdrv1" %}
{% set version = "1.0.0" %}  # Update to your tagged release

package:
  name: {{ name }}
  version: {{ version }}

source:
  # For conda-forge staged-recipes, prefer a tarball URL + sha256
  url: https://github.com/xlbbb-cn/gr-sdrv1/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0000000000000000000000000000000000000000000000000000000000000000  # REPLACE

build:
  number: 0
  # compiled extension + python module -> platform-specific
  script:
    - bash -ex recipe/build.sh  # [unix]
    - call recipe\bld.bat       # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    - python
    - pybind11
    - pygccxml
  host:
    - python
    - gnuradio
    - libiio
    - numpy
    - pylibiio
  run:
    - python
    - gnuradio
    - libiio
    - numpy
    - pylibiio

test:
  commands:
    - python -c "import gnuradio, gnuradio.sdrv1; print(getattr(gnuradio.sdrv1, '__doc__', '')[:10])"

about:
  home: https://github.com/xlbbb-cn/gr-sdrv1
  summary: GNU Radio OOT module for SDRV1 hardware via libiio
  description: |
    gr-sdrv1 提供 SDRV1 设备的收发块（C++/Python）和 GRC 支持，使用 libiio 与设备通信。
  license: GPL-3.0-or-later  # 或 MIT；必须与仓库保持一致并提供 license_file
  license_file: LICENSE
  doc_url: https://github.com/xlbbb-cn/gr-sdrv1
  dev_url: https://github.com/xlbbb-cn/gr-sdrv1

extra:
  recipe-maintainers:
    - xlbbb-cn
