/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sdrv1stream_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c9e37de40260205756238eb0441592b1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sdrv1/sdrv1stream_sink.h>
// pydoc.h is automatically generated in the build directory
#include <sdrv1stream_sink_pydoc.h>

void bind_sdrv1stream_sink(py::module& m)
{

    using sdrv1stream_sink    = gr::sdrv1::sdrv1stream_sink;


    py::class_<sdrv1stream_sink, gr::block, gr::basic_block,
        std::shared_ptr<sdrv1stream_sink>>(m, "sdrv1stream_sink", D(sdrv1stream_sink))

        .def(py::init(&sdrv1stream_sink::make),
           py::arg("ip_addr"),
           py::arg("chn"),
           py::arg("bufsize"),
           D(sdrv1stream_sink,make)
        )
        



        ;




}








