/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-sdrv1
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_SDRV1_API_H
#define INCLUDED_SDRV1_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_sdrv1_EXPORTS
#define SDRV1_API __GR_ATTR_EXPORT
#else
#define SDRV1_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_SDRV1_API_H */
